[versions]
# @pin
agp = "8.13.1"
# @keep
android-compileSdk = "36"
# @keep
android-minSdk = "24"
ben-manes-versions-v = "0.53.0"
dc-aviator = "1.0.0-SNAPSHOT"
dc-polyfill = "1.0.0-SNAPSHOT"
dc-weaver = "1.0.0-SNAPSHOT"
dependency-analysis-v = "3.5.1"
koin = "4.1.1"
koin-annotations = "2.3.1"
kotlin = "2.2.21"
kotlinx-datetime = "0.7.1-0.6.x-compat"
ksp = "2.3.3"
ktor = "3.3.3"
mlln-geokit = "1.0.0-SNAPSHOT"
mlln-units = "1.0.0-SNAPSHOT"
serialization = "1.9.0"
version-catalog-update-v = "1.0.1"
xml = "0.91.3"
mapLibre-spatialk = "0.6.1"

[libraries]
dc-aviator-adapter-json = { module = "cloud.mallne.dicentra.aviator.plugin.adapter:adapter-json", version.ref = "dc-aviator" }
dc-aviator-adapter-xml = { module = "cloud.mallne.dicentra.aviator.plugin.adapter:adapter-xml", version.ref = "dc-aviator" }
dc-aviator-client-ktor = { module = "cloud.mallne.dicentra.aviator.client:ktor", version.ref = "dc-aviator" }
dc-aviator-core = { module = "cloud.mallne.dicentra.aviator:core", version.ref = "dc-aviator" }
dc-aviator-koas = { module = "cloud.mallne.dicentra.aviator:koas", version.ref = "dc-aviator" }
dc-aviator-plugin-interception = { module = "cloud.mallne.dicentra.aviator.plugin:interception", version.ref = "dc-aviator" }
dc-aviator-plugin-synapse = { module = "cloud.mallne.dicentra.aviator.plugin:synapse", version.ref = "dc-aviator" }
dc-aviator-plugin-weaver = { module = "cloud.mallne.dicentra.aviator.plugin:weaver", version.ref = "dc-aviator" }
dc-polyfill = { module = "cloud.mallne.dicentra:polyfill", version.ref = "dc-polyfill" }
dc-weaver-core = { module = "cloud.mallne.dicentra.weaver:core", version.ref = "dc-weaver" }
dc-weaver-tokenizer = { module = "cloud.mallne.dicentra.weaver:tokenizer", version.ref = "dc-weaver" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
mlln-geokit-calculation = { module = "cloud.mallne.geokit:calculation", version.ref = "mlln-geokit" }
mlln-geokit-coordinates = { module = "cloud.mallne.geokit:coordinates", version.ref = "mlln-geokit" }
mlln-geokit-geojson = { module = "cloud.mallne.geokit:geojson", version.ref = "mlln-geokit" }
mlln-geokit-ogc = { module = "cloud.mallne.geokit:ogc", version.ref = "mlln-geokit" }
mlln-geokit-interop = { module = "cloud.mallne.geokit:interop", version.ref = "mlln-geokit" }
mlln-units = { module = "cloud.mallne:units", version.ref = "mlln-units" }
xml = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xml" }
maplibre-spatialk = { module = "org.maplibre.spatialk:geojson", version.ref = "mapLibre-spatialk" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "ben-manes-versions-v" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis-v" }
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
mavenPublish = "com.vanniktech.maven.publish:0.35.0"
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update-v" }
